services:
  auction-database:
    image: postgres
    container_name: auction-database
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: